// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    ElIconArrowRight: typeof import('@element-plus/icons-vue')['ArrowRight']
    ElIconAuth: typeof import('@element-plus/icons-vue')['Auth']
    ElIconCollapse: typeof import('@element-plus/icons-vue')['Collapse']
    ElIconExpand: typeof import('@element-plus/icons-vue')['Expand']
    ElIconFold: typeof import('@element-plus/icons-vue')['Fold']
    ElIconLocation: typeof import('@element-plus/icons-vue')['Location']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElIconMenuFold: typeof import('@element-plus/icons-vue')['MenuFold']
    ElIconMenuUnfold: typeof import('@element-plus/icons-vue')['MenuUnfold']
    ElIconSetUp: typeof import('@element-plus/icons-vue')['SetUp']
    ElIconUser: typeof import('@element-plus/icons-vue')['User']
    ElIconUserFilled: typeof import('@element-plus/icons-vue')['UserFilled']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
  }
}
