name: 自动发布

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 1. 检查master分支
        uses: actions/checkout@v3

      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. 缓存
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

      - name: 4. 安装依赖
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          yarn install

      - name: 5. 生成文件
        run: |
          export TZ='Asia/Shanghai'
          yarn build

      - name: 6. 读取当前版本号
        id: version
        run: |
          export TZ='Asia/Shanghai'
          echo "value=$(node ./scripts/ci-version.cjs)" >> $GITHUB_OUTPUT

      - name: 7. 创建压缩包
        id: build_zip
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "dist"
          zipFilePath: "MR-Extension v${{steps.version.outputs.value}}.zip"

      - name: 8. 创建GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.version.outputs.value}}
          body: MR Extension 是一个 Chrome 插件，需要与 Movie Bot 配合使用。 用于将当前浏览器登陆过的PT站点提交到 Movie Bot 中。
          draft: false
          prerelease: false
          files: MR-Extension v${{steps.version.outputs.value}}.zip

      - name: 9. 更新 Release Note
        run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
